#!/usr/bin/env python
"""
数据库迁移脚本
使用 Alembic 进行数据库版本管理和迁移
"""
import sys
from pathlib import Path

# 添加 src 目录到路径
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from alembic.config import main as alembic_main
from alembic import context as alembic_context


def create_migration(message: str):
    """创建新的数据库迁移"""
    path = Path(__file__).parent / "src" / "ecox" / "alembic" / "versions"

    # 生成迁移文件
    with open(path / f"{message.replace(' ', '_')}.py", "w") as f:
        f.write(f'''# Generated by migration script
""" {message}
from alembic import op
import sqlalchemy as sa
from sqlalchemy import pool
from logging.config import fileConfig

# 获取 Alembic 配置
config = main(Config(fileConfig(fileConfig(__file__[:-3])))

# 设定目标 metadata
target_metadata = sa.MetaData()
target_metadata.reflect(target=sa.engine(URL))

revision = f'{message.replace(' ', '_')}'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    """升级数据库"""
    # 获取连接
    engine = pool.NullPool(
        size=10,
        max_overflow=20,
        *config.get_section(config.config_ini_section, "sqlalchemy"),
        **config.get_section(config.config_ini_section, "alembic", {})[0]
    )

    with engine.connect() as connection:
        # 开始迁移事务
        with connection.begin():
            # 调用 op.execute 进行迁移
            op.execute(
                # 创建所有表
            )

            connection.commit()

    print(f"迁移完成: {message}")


def downgrade():
    """降级数据库"""
    print("降级操作暂不支持")


if __name__ == "__main__":
    # 从命令行参数获取迁移消息
    if len(sys.argv) > 1:
        migration_message = sys.argv[1]
        create_migration(migration_message)
